name: generate snake

on:
  # Run automatically every 6 hours
  schedule:
    - cron: '0 */6 * * *'

  # Allows to manually run the job at any time
  workflow_dispatch:

  # Run on every push on the master branch
  push:
    branches:
      - master  # 注意: 如果默认分支为main，请修改此处

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository before processing
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create the output directory if it does not exist
      - name: Create output directory
        run: mkdir -p dist

      # Generates a snake game from a GitHub user contributions graph
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      # Push the content of <build_dir> to a branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
