name: Waka Readme

on:
  push:
    branches:
      - main
      - release/*
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
          uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: echo "API_KEY=$API_KEY\nAPI_SECRET=$API_SECRET" >> .env

      - name: Update Readme
        uses: nick22985/Dev-Stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Github Summary
          SHOW_SHORT_INFO: true # optional, default is true
          # Shows language activity for that week
          SHOW_BREAK_DOWN: true # optional, default is true
          # Shows timezone. Requires SHOW_BREAK_DOWN=true
          SHOW_TIMEZONE: false  # optional, default is true
          # Shows editors used in the week SHOW_BREAK_DOWN=true
          SHOW_EDITORS: true # optional, default is true
          # Show week coding language breakdown
          SHOW_LANGUAGES: true # optional, default is true
          # Shows Operating System
          SHOW_OS: false # optional, default is true
          # Show Hostnames of computers
          SHOW_HOSTS: false # optional, default is true
          # Shows github repo language counts
          SHOW_LANGUAGE_PER_REPO: false # optional, default is true
          # Show Projects worked on that week
          SHOW_PROJECTS: false # optional, default is true
