name: Build Graph

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  update-readme:
    name: Update this repo's README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history for pushing

      - name: Set up Git
        run: |
          git config user.name "AITuring"
          git config user.email "shspku365@gmail.com"

      - name: Create new branch
        run: |
          git branch -f wakatime || git checkout -b wakatime
          git checkout wakatime

      - name: Generate WakaTime stats
        uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_MSG: "new stats received :dog:"
          STATS_RANGE: last_30_days

      - name: Push changes
        run: |
          git add .
          git commit -m "Update WakaTime stats"
          git push origin wakatime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
